name: Build and Publish to Docker Hub
on:
  workflow_dispatch:

jobs:
  publish_images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image: neyocicd/devops-qr-api:latest
            context: ./api
            file: ./api/Dockerfile
          - image: neyocicd/devops-qr-code-frontend:latest
            context: ./front-end-nextjs
            file: ./front-end-nextjs/Dockerfile

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push ${{ matrix.image }}
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          file:    ${{ matrix.file }}
          push:    true
          tags:    ${{ matrix.image }}
